version: '3.8'

services:
  database:
    image: mongo:6.0
    container_name: database
    ports:
      - "27017:27017"
    command:
      - "--replSet"
      - "rs0"
      - "--bind_ip_all"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
