services:
  database:
    image: mongo:6.0
    container_name: database
    ports:
      - "27017:27017"
    command:
      - "--replSet"
      - "rs0"
      - "--bind_ip_all"
    volumes:
      - mongodb_data:/data/db
    networks:
      - main
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    container_name: app
    depends_on:
      - database
    ports:
      - 80:80
      - 443:443
    networks:
      - main
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    container_name: api
    depends_on:
      - database
    ports:
      - 3000:3000
    networks:
      - main
    volumes:
      - ./.env:/opt/app/.env

networks:
  main:
    driver: bridge

volumes:
  mongodb_data:
