services:
  database:
    image: mongo:8.0.9
    container_name: database
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"] 

volumes:
  mongodb_data: