version: '3.8'

services:
  database:
    image: mongo:8.0.9
    container_name: database
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: main
    volumes:
      - mongodb_data:/data/db